package com.chariot.jpademo.revengdemo;
// Generated Aug 12, 2011 5:43:50 PM by Hibernate Tools 3.2.2.GA


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * HibernateSequences generated by hbm2java
 */
@Entity
@Table(name="hibernate_sequences"
    ,catalog="coursemgrch4"
)
public class HibernateSequences  implements java.io.Serializable {


     private HibernateSequencesId id;

    public HibernateSequences() {
    }

    public HibernateSequences(HibernateSequencesId id) {
       this.id = id;
    }
   
     @EmbeddedId
    
    @AttributeOverrides( {
        @AttributeOverride(name="sequenceName", column=@Column(name="sequence_name") ), 
        @AttributeOverride(name="sequenceNextHiValue", column=@Column(name="sequence_next_hi_value") ) } )
    public HibernateSequencesId getId() {
        return this.id;
    }
    
    public void setId(HibernateSequencesId id) {
        this.id = id;
    }




}


