package com.chariot.jpademo.revengdemo;
// Generated Aug 12, 2011 5:43:50 PM by Hibernate Tools 3.2.2.GA


import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Version;

/**
 * Instructor generated by hbm2java
 */
@Entity
@Table(name="instructor"
    ,catalog="coursemgrch4"
)
public class Instructor  implements java.io.Serializable {


     private long id;
     private Integer version;
     private String addressLine1;
     private String addressLine2;
     private String city;
     private String emailAddress;
     private String firstName;
     private String lastName;
     private String middleNameOrInitial;
     private String postalCode;
     private String stateCode;
     private boolean active;
     private String taxNumber;
     private Set<Offering> offerings = new HashSet<Offering>(0);

    public Instructor() {
    }

	
    public Instructor(long id, String addressLine1, String city, String emailAddress, String lastName, String postalCode, String stateCode, boolean active, String taxNumber) {
        this.id = id;
        this.addressLine1 = addressLine1;
        this.city = city;
        this.emailAddress = emailAddress;
        this.lastName = lastName;
        this.postalCode = postalCode;
        this.stateCode = stateCode;
        this.active = active;
        this.taxNumber = taxNumber;
    }
    public Instructor(long id, String addressLine1, String addressLine2, String city, String emailAddress, String firstName, String lastName, String middleNameOrInitial, String postalCode, String stateCode, boolean active, String taxNumber, Set<Offering> offerings) {
       this.id = id;
       this.addressLine1 = addressLine1;
       this.addressLine2 = addressLine2;
       this.city = city;
       this.emailAddress = emailAddress;
       this.firstName = firstName;
       this.lastName = lastName;
       this.middleNameOrInitial = middleNameOrInitial;
       this.postalCode = postalCode;
       this.stateCode = stateCode;
       this.active = active;
       this.taxNumber = taxNumber;
       this.offerings = offerings;
    }
   
     @Id 
    
    @Column(name="id", unique=true, nullable=false)
    public long getId() {
        return this.id;
    }
    
    public void setId(long id) {
        this.id = id;
    }
    @Version
    @Column(name="version")
    public Integer getVersion() {
        return this.version;
    }
    
    public void setVersion(Integer version) {
        this.version = version;
    }
    
    @Column(name="address_line1", nullable=false, length=60)
    public String getAddressLine1() {
        return this.addressLine1;
    }
    
    public void setAddressLine1(String addressLine1) {
        this.addressLine1 = addressLine1;
    }
    
    @Column(name="address_line2", length=60)
    public String getAddressLine2() {
        return this.addressLine2;
    }
    
    public void setAddressLine2(String addressLine2) {
        this.addressLine2 = addressLine2;
    }
    
    @Column(name="city", nullable=false, length=40)
    public String getCity() {
        return this.city;
    }
    
    public void setCity(String city) {
        this.city = city;
    }
    
    @Column(name="email_address", nullable=false, length=80)
    public String getEmailAddress() {
        return this.emailAddress;
    }
    
    public void setEmailAddress(String emailAddress) {
        this.emailAddress = emailAddress;
    }
    
    @Column(name="first_name", length=30)
    public String getFirstName() {
        return this.firstName;
    }
    
    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }
    
    @Column(name="last_name", nullable=false, length=30)
    public String getLastName() {
        return this.lastName;
    }
    
    public void setLastName(String lastName) {
        this.lastName = lastName;
    }
    
    @Column(name="middle_name_or_initial", length=30)
    public String getMiddleNameOrInitial() {
        return this.middleNameOrInitial;
    }
    
    public void setMiddleNameOrInitial(String middleNameOrInitial) {
        this.middleNameOrInitial = middleNameOrInitial;
    }
    
    @Column(name="postal_code", nullable=false, length=10)
    public String getPostalCode() {
        return this.postalCode;
    }
    
    public void setPostalCode(String postalCode) {
        this.postalCode = postalCode;
    }
    
    @Column(name="state_code", nullable=false, length=2)
    public String getStateCode() {
        return this.stateCode;
    }
    
    public void setStateCode(String stateCode) {
        this.stateCode = stateCode;
    }
    
    @Column(name="active", nullable=false)
    public boolean isActive() {
        return this.active;
    }
    
    public void setActive(boolean active) {
        this.active = active;
    }
    
    @Column(name="tax_number", nullable=false, length=9)
    public String getTaxNumber() {
        return this.taxNumber;
    }
    
    public void setTaxNumber(String taxNumber) {
        this.taxNumber = taxNumber;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="instructor")
    public Set<Offering> getOfferings() {
        return this.offerings;
    }
    
    public void setOfferings(Set<Offering> offerings) {
        this.offerings = offerings;
    }




}


