package com.chariot.jpademo.revengdemo;
// Generated Aug 12, 2011 5:43:50 PM by Hibernate Tools 3.2.2.GA


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Version;

/**
 * Invoice generated by hbm2java
 */
@Entity
@Table(name="invoice"
    ,catalog="coursemgrch4"
)
public class Invoice  implements java.io.Serializable {


     private Integer invoiceId;
     private Integer version;
     private BigDecimal amount;
     private Date dueDate;
     private String emailAddress;
     private String studentName;
     private Set<Payment> payments = new HashSet<Payment>(0);

    public Invoice() {
    }

	
    public Invoice(BigDecimal amount, Date dueDate, String emailAddress, String studentName) {
        this.amount = amount;
        this.dueDate = dueDate;
        this.emailAddress = emailAddress;
        this.studentName = studentName;
    }
    public Invoice(BigDecimal amount, Date dueDate, String emailAddress, String studentName, Set<Payment> payments) {
       this.amount = amount;
       this.dueDate = dueDate;
       this.emailAddress = emailAddress;
       this.studentName = studentName;
       this.payments = payments;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="invoice_id", unique=true, nullable=false)
    public Integer getInvoiceId() {
        return this.invoiceId;
    }
    
    public void setInvoiceId(Integer invoiceId) {
        this.invoiceId = invoiceId;
    }
    @Version
    @Column(name="version")
    public Integer getVersion() {
        return this.version;
    }
    
    public void setVersion(Integer version) {
        this.version = version;
    }
    
    @Column(name="amount", nullable=false, precision=7)
    public BigDecimal getAmount() {
        return this.amount;
    }
    
    public void setAmount(BigDecimal amount) {
        this.amount = amount;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="due_date", nullable=false, length=19)
    public Date getDueDate() {
        return this.dueDate;
    }
    
    public void setDueDate(Date dueDate) {
        this.dueDate = dueDate;
    }
    
    @Column(name="email_address", nullable=false, length=80)
    public String getEmailAddress() {
        return this.emailAddress;
    }
    
    public void setEmailAddress(String emailAddress) {
        this.emailAddress = emailAddress;
    }
    
    @Column(name="student_name", nullable=false, length=80)
    public String getStudentName() {
        return this.studentName;
    }
    
    public void setStudentName(String studentName) {
        this.studentName = studentName;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="invoice")
    public Set<Payment> getPayments() {
        return this.payments;
    }
    
    public void setPayments(Set<Payment> payments) {
        this.payments = payments;
    }




}


