package com.chariot.jpademo.revengdemo;
// Generated Aug 12, 2011 5:43:50 PM by Hibernate Tools 3.2.2.GA


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Version;

/**
 * Offering generated by hbm2java
 */
@Entity
@Table(name="offering"
    ,catalog="coursemgrch4"
)
public class Offering  implements java.io.Serializable {


     private Long id;
     private Integer version;
     private Course course;
     private Instructor instructor;
     private Date runDate;
     private Set<Registration> registrations = new HashSet<Registration>(0);

    public Offering() {
    }

    public Offering(Course course, Instructor instructor, Date runDate, Set<Registration> registrations) {
       this.course = course;
       this.instructor = instructor;
       this.runDate = runDate;
       this.registrations = registrations;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="id", unique=true, nullable=false)
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }
    @Version
    @Column(name="version")
    public Integer getVersion() {
        return this.version;
    }
    
    public void setVersion(Integer version) {
        this.version = version;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="course")
    public Course getCourse() {
        return this.course;
    }
    
    public void setCourse(Course course) {
        this.course = course;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="instructor")
    public Instructor getInstructor() {
        return this.instructor;
    }
    
    public void setInstructor(Instructor instructor) {
        this.instructor = instructor;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="run_date", length=19)
    public Date getRunDate() {
        return this.runDate;
    }
    
    public void setRunDate(Date runDate) {
        this.runDate = runDate;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="offering")
    public Set<Registration> getRegistrations() {
        return this.registrations;
    }
    
    public void setRegistrations(Set<Registration> registrations) {
        this.registrations = registrations;
    }




}


