package com.chariot.jpademo.revengdemo;
// Generated Aug 12, 2011 5:43:50 PM by Hibernate Tools 3.2.2.GA


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * PaymentId generated by hbm2java
 */
@Embeddable
public class PaymentId  implements java.io.Serializable {


     private int invoiceId;
     private int paymentId;

    public PaymentId() {
    }

    public PaymentId(int invoiceId, int paymentId) {
       this.invoiceId = invoiceId;
       this.paymentId = paymentId;
    }
   

    @Column(name="invoice_id", nullable=false)
    public int getInvoiceId() {
        return this.invoiceId;
    }
    
    public void setInvoiceId(int invoiceId) {
        this.invoiceId = invoiceId;
    }

    @Column(name="payment_id", nullable=false)
    public int getPaymentId() {
        return this.paymentId;
    }
    
    public void setPaymentId(int paymentId) {
        this.paymentId = paymentId;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof PaymentId) ) return false;
		 PaymentId castOther = ( PaymentId ) other; 
         
		 return (this.getInvoiceId()==castOther.getInvoiceId())
 && (this.getPaymentId()==castOther.getPaymentId());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getInvoiceId();
         result = 37 * result + this.getPaymentId();
         return result;
   }   


}


