package com.chariot.jpademo.revengdemo;
// Generated Aug 12, 2011 5:43:50 PM by Hibernate Tools 3.2.2.GA


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Version;

/**
 * Registration generated by hbm2java
 */
@Entity
@Table(name="registration"
    ,catalog="coursemgrch4"
)
public class Registration  implements java.io.Serializable {


     private Long id;
     private Integer version;
     private Student student;
     private Offering offering;
     private boolean attended;
     private boolean paymentMade;

    public Registration() {
    }

	
    public Registration(boolean attended, boolean paymentMade) {
        this.attended = attended;
        this.paymentMade = paymentMade;
    }
    public Registration(Student student, Offering offering, boolean attended, boolean paymentMade) {
       this.student = student;
       this.offering = offering;
       this.attended = attended;
       this.paymentMade = paymentMade;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="id", unique=true, nullable=false)
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }
    @Version
    @Column(name="version")
    public Integer getVersion() {
        return this.version;
    }
    
    public void setVersion(Integer version) {
        this.version = version;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="student")
    public Student getStudent() {
        return this.student;
    }
    
    public void setStudent(Student student) {
        this.student = student;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="offering")
    public Offering getOffering() {
        return this.offering;
    }
    
    public void setOffering(Offering offering) {
        this.offering = offering;
    }
    
    @Column(name="attended", nullable=false)
    public boolean isAttended() {
        return this.attended;
    }
    
    public void setAttended(boolean attended) {
        this.attended = attended;
    }
    
    @Column(name="payment_made", nullable=false)
    public boolean isPaymentMade() {
        return this.paymentMade;
    }
    
    public void setPaymentMade(boolean paymentMade) {
        this.paymentMade = paymentMade;
    }




}


