package com.chariot.jpademo.revengdemo;
// Generated Aug 12, 2011 5:43:50 PM by Hibernate Tools 3.2.2.GA


import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.Table;
import javax.persistence.Version;

/**
 * Tag generated by hbm2java
 */
@Entity
@Table(name="tag"
    ,catalog="coursemgrch4"
)
public class Tag  implements java.io.Serializable {


     private Long id;
     private Integer version;
     private String description;
     private String tag;
     private Set<Course> courses = new HashSet<Course>(0);
     private Set<Course> courses_1 = new HashSet<Course>(0);

    public Tag() {
    }

	
    public Tag(String description, String tag) {
        this.description = description;
        this.tag = tag;
    }
    public Tag(String description, String tag, Set<Course> courses, Set<Course> courses_1) {
       this.description = description;
       this.tag = tag;
       this.courses = courses;
       this.courses_1 = courses_1;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="id", unique=true, nullable=false)
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }
    @Version
    @Column(name="version")
    public Integer getVersion() {
        return this.version;
    }
    
    public void setVersion(Integer version) {
        this.version = version;
    }
    
    @Column(name="description", nullable=false, length=250)
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    
    @Column(name="tag", nullable=false, length=25)
    public String getTag() {
        return this.tag;
    }
    
    public void setTag(String tag) {
        this.tag = tag;
    }
@ManyToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY)
    @JoinTable(name="tag_courses", catalog="coursemgrch4", joinColumns = { 
        @JoinColumn(name="tags", nullable=false, updatable=false) }, inverseJoinColumns = { 
        @JoinColumn(name="courses", nullable=false, updatable=false) })
    public Set<Course> getCourses() {
        return this.courses;
    }
    
    public void setCourses(Set<Course> courses) {
        this.courses = courses;
    }
@ManyToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY)
    @JoinTable(name="tag_associations", catalog="coursemgrch4", joinColumns = { 
        @JoinColumn(name="tag_id", nullable=false, updatable=false) }, inverseJoinColumns = { 
        @JoinColumn(name="course_id", nullable=false, updatable=false) })
    public Set<Course> getCourses_1() {
        return this.courses_1;
    }
    
    public void setCourses_1(Set<Course> courses_1) {
        this.courses_1 = courses_1;
    }




}


