package com.chariot.jpademo.revengdemo;
// Generated Aug 12, 2011 5:43:50 PM by Hibernate Tools 3.2.2.GA


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Version;

/**
 * TrainingProgram generated by hbm2java
 */
@Entity
@Table(name="training_program"
    ,catalog="coursemgrch4"
)
public class TrainingProgram  implements java.io.Serializable {


     private Long id;
     private Integer version;
     private String name;

    public TrainingProgram() {
    }

    public TrainingProgram(String name) {
       this.name = name;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="id", unique=true, nullable=false)
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }
    @Version
    @Column(name="version")
    public Integer getVersion() {
        return this.version;
    }
    
    public void setVersion(Integer version) {
        this.version = version;
    }
    
    @Column(name="name")
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }




}


